server.port=8081
server.error.include-message=always
server.error.include-binding-errors=always
spring.application.name=HealthConnect

# --- CONEXIUNE AZURE SQL DATABASE ---
# Înlocuiește NUME_SERVER, USER și PAROLA cu datele tale din Azure Portal
spring.datasource.url=jdbc:sqlserver://healthconnect-sql-server-2026.database.windows.net:1433;database=healthconnect-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=adrianfl24
spring.datasource.password=rapid1923bU1
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- CONFIGURARE JPA / HIBERNATE ---
# Setează 'update' pentru ca Hibernate să creeze/actualizeze tabelele automat pe Azure
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
